Allow to specify source database instead of defaulting to bronze database in __get_silver_dataflow_spec_dataframe
databrickslabs/dlt-meta pull request #34
Opened 2024-01-22 15:45 UTC by rtdtwo

## Issue
The FAQs describes that any data source can be used for silver tables. However, the code always tries to find the bronze database from the onboarding rows, and there's no explicit mention of a source database other than a bronze database.

## Fix
Change the code to accomplish the following:
- Use `bronze_database_{env}` if the field is found in onboarding rows.
- If not, find and use `source_details`.

2024-01-22 17:51 UTC, ravi-databricks approved these changes
LGTM

2024-01-22 17:55 UTC, ravi-databricks requested changes
Please fix [Linting  errors](https://github.com/databrickslabs/dlt-meta/actions/runs/7613717143/job/20739472484)

2024-01-22 23:12 UTC, ravi-databricks commented
@rtdtwo, Needs to add unit tests for added new lines as per above code coverage report.

2024-01-28 19:50 UTC, jaceklaskowski commented on src/onboard_dataflowspec.py
> +                    "database": onboarding_row["bronze_database_{}".format(env)],
Why not use `f"bronze_database_{env}"` as in `if` above (which IMHO is more pythonic)?

2024-12-04 20:44 UTC, ravi-databricks commented
Closing this PR since its very old and author did not followup on review changes.

2024-12-04 20:44 UTC, closed without merging